shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

env:
    TERM: xterm-256color
    #TERM: alacritty
    COLORTERM: truecolor


window:
    title: Alacritty
    dynamic_title: true
    class:
        instance: Alacritty
        general: Alacritty
    padding:
        x: 4
        y: 4


scrolling:
    history: 100000


font:
    normal:
        family: FiraCode Nerd Font
        style: Regular

    #bold:
    #   style: Bold
    #
    #italic:
    #   style: Italic

    size: 8

    offset:
        x: 0
        y: 0

    glyph_offset:
        x: 0
        y: 0

    AppleFontSmoothing: true


draw_bold_text_with_bright_colors: true

# Background opacity
#background_opacity: 0.86


bell:
    animaton: EaseOutExpo
    duration: 0


mouse_bindings:
  - { mouse: Middle, action: PasteSelection }


mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true


selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"


live_config_reload: true


cursor:
    style:
        blinking: On
    unfocused_hollow: true


schemes:
    gruvbox: &gruvbox
      # Default colors
      primary:
        # hard contrast: background = '0x1d2021'
        background: '0x282828'
        # soft contrast: background = '0x32302f'
        foreground: '0xebdbb2'

      # Normal colors
      normal:
        black:   '0x282828'
        red:     '0xcc241d'
        green:   '0x98971a'
        yellow:  '0xd79921'
        blue:    '0x458588'
        magenta: '0xb16286'
        cyan:    '0x689d6a'
        white:   '0xa89984'

      # Bright colors
      bright:
        black:   '0x928374'
        red:     '0xfb4934'
        green:   '0xb8bb26'
        yellow:  '0xfabd2f'
        blue:    '0x83a598'
        magenta: '0xd3869b'
        cyan:    '0x8ec07c'
        white:   '0xebdbb2'
    nord: &nord
        primary:
            background: '#2e3440'
            foreground: '#d8dee9'
            dim_foreground: '#a5abb6'
        cursor:
            text: '#2e3440'
            cursor: '#d8dee9'
        vi_mode_cursor:
            text: '#2e3440'
            cursor: '#d8dee9'
        selection:
            text: CellForeground
            background: '#4c566a'
        search:
            matches:
                foreground: CellBackground
                background: '#88c0d0'
            colors.footer_bar:
                background: '#434c5e'
                foreground: '#d8dee9'
        normal:
            black: '#3b4252'
            red: '#bf616a'
            green: '#a3be8c'
            yellow: '#ebcb8b'
            blue: '#81a1c1'
            magenta: '#b48ead'
            cyan: '#88c0d0'
            white: '#e5e9f0'
        bright:
            black: '#4c566a'
            red: '#bf616a'
            green: '#a3be8c'
            yellow: '#ebcb8b'
            blue: '#81a1c1'
            magenta: '#b48ead'
            cyan: '#8fbcbb'
            white: '#eceff4'
        dim:
            black: '#373e4d'
            red: '#94545d'
            green: '#809575'
            yellow: '#b29e75'
            blue: '#68809a'
            magenta: '#8c738c'
            cyan: '#6d96a5'
            white: '#aeb3bb'

    dracula: &dracula
        primary:
            background: '#282a36'
            foreground: '#f8f8f2'
            bright_foreground: '#ffffff'
        cursor:
            text: CellBackground
            cursor: CellForeground
        vi_mode_cursor:
            text: CellBackground
            cursor: CellForeground
        search:
            matches:
                foreground: '#44475a'
                background: '#50fa7b'
            focused_match:
                foreground: '#44475a'
                background: '#ffb86c'
            colors.footer_bar:
                background: '#282a36'
                foreground: '#f8f8f2'
        hints:
            start:
                foreground: '#282a36'
                background: '#f1fa8c'
            end:
                foreground: '#f1fa8c'
                background: '#282a36'
        line_indicator:
            foreground: None
            background: None
        selection:
            text: CellForeground
            background: '#44475a'
        normal:
            black: '#21222c'
            red: '#ff5555'
            green: '#50fa7b'
            yellow: '#f1fa8c'
            blue: '#bd93f9'
            magenta: '#ff79c6'
            cyan: '#8be9fd'
            white: '#f8f8f2'
        bright:
            black: '#6272a4'
            red: '#ff6e6e'
            green: '#69ff94'
            yellow: '#ffffa5'
            blue: '#d6acff'
            magenta: '#ff92df'
            cyan: '#a4ffff'
            white: '#ffffff'

    juno: &juno
        primary:
            background: "#151821"
            foreground: "#c4c5c7"
            cursor: "#c4c5c7"
        normal:
            black: "#151821"
            red: "#6e7aaa"
            green: "#7b82aa"
            yellow: "#8887aa"
            blue: "#a288a4"
            magenta: "#aa6c7b"
            cyan: "#b95055"
            white: "#c4c5c7"
        bright:
            black: "#4f5158"
            red: "#6e7aaa"
            green: "#7b82aa"
            yellow: "#8887aa"
            blue: "#a288a4"
            magenta: "#aa6c7b"
            cyan: "#b95055"
            white: "#c4c5c7"

    pop: &pop
        primary:
            background: '#333333'
            foreground: '#F2F2F2'
        normal:
            black:   '#333333'
            red:     '#CC0000'
            green:   '#4E9A06'
            yellow:  '#C4A000'
            blue:    '#3465A4'
            magenta: '#75507B'
            cyan:    '#06989A'
            white:   '#D3D7CF'
        bright:
            black:   '#88807C'
            red:     '#F15D22'
            green:   '#73C48F'
            yellow:  '#FFCE51'
            blue:    '#48B9C7'
            magenta: '#AD7FA8'
            cyan:    '#34E2E2'
            white:   '#EEEEEC'


colors: *gruvbox


# Keybindings.
key_bindings:
    - { key: NumpadAdd,         mods: Control,  action: IncreaseFontSize  }
    - { key: NumpadSubtract,    mods: Control,  action: DecreaseFontSize  }
    - { key: Key0,    mods: Control,  action: ResetFontSize     }
