// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.





user_pref("accessibility.typeaheadfind.flashBar", 0);

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);

user_pref("breakpad.reportURL", "");

user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.bookmarks.showMobileBookmarks", false);
user_pref("general.buildID.override", "20100101");
user_pref("browser.cache.offline.enable",false);
user_pref("browser.chrome.site_icons",false);
user_pref("browser.compactmode.show", true);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.crashReports.unsubmittedCheck.enabled",false);
user_pref("browser.discovery.enabled", false);
user_pref("browser.display.use_document_fonts",0);
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.ctrlTab.has-used", true);
user_pref("browser.engagement.fxa-toolbar-menu-button.has-used", true);
user_pref("browser.firefox-view.view-count", 8);
user_pref("browser.formfill.enable", false);
user_pref("browser.laterrun.bookkeeping.sessionCount", 34);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories",false);
user_pref("browser.newtab.url", "about:blank");
user_pref("browser.newtabpage.activity-stream.enabled",false);
user_pref("browser.newtabpage.enhanced",false);
user_pref("browser.newtab.preload",false);
user_pref("browser.newtabpage.directory.ping", "");
user_pref("browser.newtabpage.directory.source", "data:text/plain,{}");
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr",false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets",false);
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.pocket.enabled",false);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.blockedURIs.enabled", true);
user_pref("browser.safebrowsing.enabled",true); // Firefox < 50
user_pref("browser.safebrowsing.phishing.enabled",true); // firefox >= 50
user_pref("browser.search.countryCode", "PH");
user_pref("browser.search.geoSpecificDefaults",false);
user_pref("browser.search.hiddenOneOffs", "DuckDuckGo");
user_pref("browser.search.region", "PH");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.blankWindow", false);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage", "chrome://browser/content/blanktab.html");
user_pref("browser.startup.homepage_override.buildID", "20100101");
user_pref("browser.send_pings", false);
user_pref("browser.tabs.crashReporting.sendReport",false);
user_pref("browser.tabs.firefox-view.ui-state.tab-pickup.open", true);
user_pref("browser.tabs.inTitlebar", 0);
user_pref("browser.tabs.warnOnClose", true);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.groupLabels.enabled", false); // Firefox >= 93
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.shortcuts.bookmarks", false);
user_pref("browser.urlbar.shortcuts.history", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("browser.urlbar.showSearchSuggestionsFirst", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.suggest.topsites", false);

user_pref("camera.control.face_detection.enabled",false);

user_pref("clipboard.autocopy",false);

user_pref("datareporting.healthreport.uploadEnabled",false);
user_pref("datareporting.healthreport.service.enabled",false);
user_pref("datareporting.policy.dataSubmissionEnabled",false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);

user_pref("device.sensors.enabled",false);

user_pref("devtools.chrome.enabled",false);
user_pref("devtools.debugger.force-local",true);
user_pref("devtools.debugger.remote-enabled",false);

user_pref("distribution.iniFile.exists.value", false);

user_pref("doh-rollout.disable-heuristics", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "PH");

user_pref("dom.archivereader.enabled",false);
user_pref("dom.battery.enabled",false);
user_pref("dom.enable_performance",false);
user_pref("dom.enable_resource_timing",false);
user_pref("dom.enable_user_timing",false);
user_pref("dom.gamepad.enabled",false);
user_pref("dom.maxHardwareConcurrency",2);
user_pref("dom.security.https_only_mode", true);
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("dom.vibrator.enabled",           false);
user_pref("dom.vr.enabled",false);

user_pref("experiments.supported",false);
user_pref("experiments.enabled",false);
user_pref("experiments.manifest.uri", "");

user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.enabled",true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.pocket.onSaveRecs", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.update.enabled",true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.addons-restricted-domains@mozilla.com.domainsToPreserve", "");
user_pref("extensions.webextensions.restrictedDomains", "");

user_pref("findbar.highlightAll", true);

user_pref("gecko.handlerService.defaultHandlersVersion", 1);

user_pref("identity.fxaccounts.account.device.name", "clint@bee");

user_pref("intl.accept_languages", "en-US, en");
user_pref("intl.locale.matchOS",false);
user_pref("intl.regional_prefs.use_os_locales", true);

user_pref("javascript.use_us_english_locale",true);

user_pref("keyword.enabled",false);

user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.autoupdate", true);
user_pref("media.webspeech.recognition.enable",false);
user_pref("media.webspeech.synth.enabled",false);

user_pref("network.allow-experiments",false);
user_pref("network.dns.blockDotOnion",true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.IDN_show_punycode",true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.trr.mode", 3);

user_pref("pdfjs.disabled",true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);

user_pref("permissions.default.desktop-notification", 2);
user_pref("permissions.default.geo", 2);
user_pref("permissions.default.xr", 2);

user_pref("places.history.enabled", false);

user_pref("plugin.state.libgnome-shell-browser-plugin",0);

user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.clearOnShutdown.sessions", false);
user_pref("privacy.clearOnShutdown.siteSettings", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", true);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.trackingprotection.emailtracking.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);

user_pref("security.insecure_password.ui.enabled",true);

user_pref("services.settings.clock_skew_seconds", 913);

user_pref("signon.autofillForms", false);
user_pref("signon.generation.enabled", false);
user_pref("signon.rememberSignons", false);

user_pref("storage.vacuum.last.index", 1);

user_pref("toolkit.telemetry.archive.enabled",false);
user_pref("toolkit.telemetry.enabled",false);
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.unified",false);
user_pref("toolkit.zoomManager.zoomValues", ".3,.5,.67,.75,.8,.9,1,1.1,1.2,1.33,1.5,1.7,2,2.4,3,4,5");

user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
